/*
 * DO NOT EDIT - AutoGenerated by config.ps1
 */

#define  STDIO_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\stdio.h"
#define  STRING_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\string.h"
#define  SYS_TYPES_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\sys\types.h"
#define  CTYPE_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\ctype.h"
#define  STDLIB_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\stdlib.h"
#define  SYS_STAT_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\sys\stat.h"
#define  FCNTL_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\fcntl.h"
#define  TIME_H  "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\time.h"
